### ISSUE TITLE
La respuesta del servidor no lanza las señales

### ISSUE THREAD

**Issue by danieltellez** [bcurtu/django-sermepa#15]
En mi caso, la respuesta del servidor de redsys llama a la URL de OK, pero nunca a la de sermepa_ipn, por lo tanto no lanza nunca las señales para gestionar el OK.

Estoy utilizando el sistema de vistas basado en clases de las nuevas versiones de Django. Al principio lo intenté tal cual con el código vuestro. Luego he intentado colocar el código de sermepa_ipn en una vista basada en clases, una FormView, pero tampoco surte efecto.

Por último, he intentado gestionar lo que hace sermepa_ipn en la vista de OK, pero no recibe aquí los parámetros de respuesta.

Alguien sabe qué puede estar pasando ?

**Comment by bcurtu** [comment]
Cuando envías el post a redsys tienes que decirle cual es tu url de
callback en la variable Ds_Merchant_MerchantURL

Esta url tiene que ser pública (no vale localhost:8000). Si no tienes una
url pública, puedes crearte un tunnel con alguna herramienta como ngrok

Saludos

**Comment by danieltellez** [comment]
Oooook, entonces es por eso, la URL no es pública. Lo estaba probando en local ;-) 
GRACIAS !!

**Comment by valentinelorza** [comment]
Tengo ese mismo problena pero con la url public @danieltellez ¿al final te funciono?

**Comment by danieltellez** [comment]
A mi me funcionó, pero ya hace tiempo que dejé de usar esto. Sorry :-)
