### ISSUE TITLE
Sistema de firma antiguo

### ISSUE THREAD

**Issue by LaCharca** [bcurtu/django-sermepa#21]
Buenas,
al intentar probar la librería, me aparece un error "SIS0444". En la documentación de Redsys dice: 

**> Error producido al acceder mediante un sistema de firma antiguo teniendo configurado el tipo de clave HMAC SHA256.**

No sé si estoy haciendo algo mal o es que la librería utiliza un sistema de firma antiguo. En caso de ser la segunda opción ¿se puede corregir?

Muchas gracias y un saludo.

**Comment by bcurtu** [comment]
Hace 2 años lo cambiamos, pero en cualquier caso este paquete está muy outdated.
Te recomiendo crearte tu propia versión, haz un fork e inspírate en el código.

Saludos

**Comment by LaCharca** [comment]
Retiro lo dicho. Estaba usando una versión antigua, supongo que la inicial. Con la última versión funciona sin ningún problema. Para lo que necesito hacer me vale más que de sobra.

Gracias!!

**Comment by bcurtu** [comment]
👏 👏

**Comment by alvarovelezgalvez** [comment]
@bcurtu Doy fe de que la biblioteca sigue funcionando bien con los cambios que le hicimos hace un tiempo. Incluido Django 2.0 !


Salu2,
Álvaro.
