### ISSUE TITLE
Compatibilidad con SHA256

### ISSUE THREAD

**Issue by alvarovelezgalvez** [bcurtu/django-sermepa#3]
Hola, 

de acuerdo con esta información de RedSys https://canales.redsys.es/canales/ayuda/migracionSHA256.html
a finales de noviembre dejaran de funcionar las firmas basadas en SHA1 y por tanto dejarán de funcionar las funciones que realizan la firma (y la librería en sí, que se basa en SHA1)

He realizado unas pruebas intentando migrar los ejemplos que ofrecen (en PHP) en su documentación, pero en todo caso sigo obteniendo un error 0042 (error de firma) al enviar el formulario a su entorno. (Las pruebas hechas contra el servidor de producción de Redsys desde el script de PHP funcionan porque ya he recibido la nueva clave 256 desde mi banco).

Este sería el código que he empleado para probar:

``` python
    from pyDes import triple_des, CBC, PAD_PKCS5
    import hashlib, json, base64, hmac

    """
        Datos fijos. 
    """ 
    Ds_SignatureVersion = 'HMAC_SHA256_V1'
    new_256_key = 'aquiirialaclaveenviadaporlaentidadbancaria'
    order = "1234567890"

    """
        Creamos un json y los codificamos en base64 eliminando retornos de carro
    """ 
    merchant_parameters = {}
    merchant_parameters['DS_MERCHANT_AMOUNT'] = "1000"
    merchant_parameters['DS_MERCHANT_ORDER'] = order
    merchant_parameters['DS_MERCHANT_MERCHANTCODE'] = "XXXXXXXXXX"
    merchant_parameters['DS_MERCHANT_CURRENCY'] = "978"
    merchant_parameters['DS_MERCHANT_TRANSACTIONTYPE'] = "0"
    merchant_parameters['DS_MERCHANT_TERMINAL'] = "1"
    merchant_parameters['DS_MERCHANT_MERCHANTURL'] = "http:\\test\redsys\callback_url"
    merchant_parameters['DS_MERCHANT_URLOK'] = "http:\\test\OK"
    merchant_parameters['DS_MERCHANT_URLKO'] = "http:\\test\OK"
    parameters = (json.dumps(merchant_parameters)).encode()
    print '\n\n parameters --> %s' % parameters
    Ds_MerchantParameters = ''.join(unicode(base64.encodestring(parameters), 'utf-8').splitlines())
    print '\n\n Ds_MerchantParameters --> %s' % Ds_MerchantParameters


    """
        Se genera una clave específica por operación. Para obtener la
        clave derivada a utilizar en una operación se debe realizar un
        cifrado 3DES entre la clave del comercio y el valor del número de
        pedido de la operación (Ds_Merchant_Order).
    """
    new_256_key_decoded  = base64.b64decode(new_256_key)
    print 'new_256_key_decoded --> %s' % new_256_key_decoded
    k = triple_des(new_256_key_decoded, CBC, "\0\0\0\0\0\0\0\0", pad=None,  padmode=PAD_PKCS5)
    ciphertext  = k.encrypt(order)
    print 'ciphertext --> %s' % ciphertext


    """
        Se calcula el HMAC SHA256 del valor del parámetro
        Ds_MerchantParameters y la clave obtenida en el paso anterior.
        El resultado obtenido se codifica en BASE 64, y el resultado de la
        codificación será el valor del parámetro Ds_Signature, tal y
        como se puede observar en el ejemplo de formulario mostrado al
        inicio del apartado 3.
    """
    hmac_value = hmac.new(ciphertext, Ds_MerchantParameters, digestmod=hashlib.sha256).hexdigest()
    print 'hmac_value --> %s' % hmac_value
    Ds_Signature = base64.b64encode(hmac_value)
    print 'Ds_Signature --> %s' % Ds_Signature


    """
        Estos serían los tres parámetros a enviar a Redsys
    """
    context['Ds_SignatureVersion'] = Ds_SignatureVersion
    context['Ds_MerchantParameters'] = Ds_MerchantParameters
    context['Ds_Signature'] = Ds_Signature
```

**Comment by bcurtu** [comment]
Así a simple vista puedo ver que la firma hmac debe ser digest() en vez de hexadigest(). Dime si así avanzas.

Valida también que el triple_des lo esté haciendo bien, para descartar errores. Por ejemplo, para la ORDER = "12345" con la clave: "sq7HjrUOBfKmC576ILgskD5srU870gJ7", el resultado transformado a Base64 es "JnH2hJyiSPA=\n"

Finalmente, la firma hmac de la cadena "1234567890" con la clave generada (sin base64) es: "E0r3R9ScyRCkQ7qSuSDLrJ4Naf8wdz8ixeJ7NtHy2FY="

**Comment by alvarovelezgalvez** [comment]
Hola!
- Si, inicialmente usaba digest() en vez de hexadigest() y se me coló al pegar el código aquí.

Diría que el problema es realizar la triple_des. Estoy probando con los datos que me das y obtengo un  resultado diferente. Ejecuto:

``` python
    order = "12345"
    new_256_key = "sq7HjrUOBfKmC576ILgskD5srU870gJ7"
    k = triple_des(base64.b64decode(new_256_key), CBC, "\0\0\0\0\0\0\0\0", pad=None,  padmode=PAD_PKCS5)
    ciphertext  = k.encrypt(order)
    ciphertext_64 =  base64.b64encode(ciphertext)
    print 'order --> %s' % order
    print 'new_256_key --> %s' % new_256_key
    print 'ciphertext_64 --> %s' % ciphertext_64
```

Y obtengo:

```
order --> 12345
new_256_key --> sq7HjrUOBfKmC576ILgskD5srU870gJ7
ciphertext_64 --> emRb/Sl2LSU=
```

¿La variable new_256_key debe estar en base64 para pasarlo a la funcion triple_des verdad?

Salu2 y gracias por la pronta respuesta

**Comment by bcurtu** [comment]
Todavía no he podido hacer la integración en python, pero sí la he hecho en ruby. Así que puede que nos ayude. Mira el post que he escrito: https://engineering.sequra.es/2015/10/redsys-hmac-sha256-migration-using-ruby/

El algoritmo 3DES en php completa automáticamente (pad) la cadena de entrada con \0. En ruby lo he tenido que hacer a mano, pero parece que la librería que usas lo puede hacer con los argumentos pad y padmode:

pad     -> Optional argument. Only when using padmode of PAD_NORMAL. For
       encryption, adds this characters to the end of the data block when
       data is not a multiple of 8 bytes. For decryption, will remove the
       trailing characters that match this pad character from the last 8
       bytes of the unencrypted data block.

Prueba a poner pad=b"\0" y padmode=PAD_NORMAL a ver si funciona

**Comment by alvarovelezgalvez** [comment]
Pues parece que no, 

voy a probar otro algoritmo 3DES a ver si doy con la tecla...

**Comment by alvarovelezgalvez** [comment]
Hola de nuevo,

Pues no he conseguido avance alguno. He intentado utilizar alternativas a pyDes pero sólo encontré M2Crypto (del que apenas he encontrado documentación para 3DES); y la librería Chilkat (que he descartado al ser de pago).

Utilizando los valores que me enviaste (ORDER = "12345" con la clave: "sq7HjrUOBfKmC576ILgskD5srU870gJ7") y usando las instrucciones:

k = triple_des(new_256_key_decoded, CBC, "\0\0\0\0\0\0\0\0", pad=None,  padmode=PAD_PKCS5)
o bien
k = triple_des(key_decoded, CBC, "\0\0\0\0\0\0\0\0", pad=b"\0",  padmode=PAD_NORMAL)

obtengo dos resultados distintos pero ninguno es válido. ¿Se te ocurre alguna otra prueba que pueda realizar?

Gracias,
Álvaro.

**Comment by bcurtu** [comment]
Has visto esto en stackoverflow?
http://stackoverflow.com/questions/3541763/how-to-3des-encrypt-in-python-using-the-m2crypto-wrapper

iv deberían ser 8 bytes: iv='\0'*8

Prueba a no usar .final

Saludos

**Comment by alvarovelezgalvez** [comment]
Usando M2Crypto obtengo el mismo resultado que usando pyDes y PAD_PKCS5:

``` python
# -*- encoding: utf-8 -*-
from M2Crypto.EVP import Cipher
from pyDes import triple_des, CBC, PAD_PKCS5, PAD_NORMAL
import base64

# Key definition, decoding, and encrypt using $order
order = "12345"
key = "sq7HjrUOBfKmC576ILgskD5srU870gJ7"
key_decoded  = base64.b64decode(key)
print "\n key --> %s" % key
print "\n key_decoded --> %s" % key_decoded


# k = triple_des(key_decoded, CBC, "\0\0\0\0\0\0\0\0", pad=b"\0",  padmode=PAD_NORMAL)
k = triple_des(key_decoded, CBC, "\0\0\0\0\0\0\0\0", pad=None,  padmode=PAD_PKCS5)
ciphertext  = k.encrypt(order)
print "\n ciphertext --> %s" % ciphertext
print "\n ciphertext 64 --> %s" % base64.b64encode(ciphertext)


cipher_m2crypto = Cipher(alg="des_ede3_cbc", key=key_decoded, op=1, iv="\0"*8)
ciphertext_m2crypto = cipher_m2crypto.update(order)
ciphertext_m2crypto += cipher_m2crypto.final()
print "\n ciphertext_m2crypto --> %s" % ciphertext_m2crypto
print "\n ciphertext_m2crypto 64 --> %s" % base64.b64encode(ciphertext_m2crypto)
```

y como resultado

```
 key --> sq7HjrUOBfKmC576ILgskD5srU870gJ7
 key_decoded --> ▓«ÃÄÁ♫♣‗ª♂×· ©,É>l¡O;Ê☻{
 ciphertext --> zd[²)v-%
 ciphertext 64 --> emRb/Sl2LSU=
 ciphertext_m2crypto --> zd[²)v-%
 ciphertext_m2crypto 64 --> emRb/Sl2LSU=
```

**Comment by bcurtu** [comment]
Y si no ejecutas ciphertext_m2crypto += cipher_m2crypto.final()
qué pasa?

2015-11-02 15:38 GMT+01:00 Álvaro notifications@github.com:

**Comment by alvarovelezgalvez** [comment]
Perdón, se me pasó contestarte esa parte.

Sino ejecuto esa línea, ciphertext_m2crypto me aparece vacío.

**Comment by jordic** [comment]
Hola, yo también tengo que migrar el modulo ... :/
Algun avance? En qué parte os interesa que me ponga?

**Comment by bcurtu** [comment]
Que alguien descubra cómo hacer el 3DES correctamente. Gracias!

2015-11-04 9:44 GMT+01:00 Jordi Collell notifications@github.com:

**Comment by alvarovelezgalvez** [comment]
Hola Jordi,

Yo la parte que no he conseguido resolver es la que define Redsys como "Se genera una clave específica por operación. Para obtener la clave derivada a utilizar en una operación se debe realizar un cifrado 3DES entre la clave del comercio y el valor del número de pedido de la operación (Ds_Merchant_Order)."

He probado con la librería M2Crypto y con pyDes pero no obtengo el resultado esperado (si miras la cadena de mensajes de Bosco, él define un ejemplo de salida correcta).

Gracias!

**Comment by jordic** [comment]
A ver, partiendo de la librería php que redsys ofrece, usando el código de esta:

https://gist.github.com/jordic/331c68915b41e931824e

Si uso la key: sq7HjrUOBfKmC576ILgskD5srU870gJ7
y pedido: 00012345
En base64: HxGFaX9vsI0=
Con la misma key, y pedido 12345
25Bu+F2dMSg=

Lo cual no me cuadra con los datos que ofrecí @bcurtu.

Usando python, puedo obtener resultados iguales con:

```
from Crypt import DES3

CLAVE = 'sq7HjrUOBfKmC576ILgskD5srU870gJ7'
iv = b'\x00\x00\x00\x00\x00\x00\x00\x00'
cip = DES3.new(base64.standard_b64decode(CLAVE), DES3.MODE_CBC, IV=iv)
base64.b64_decode('00012345')
'HxGFaX9vsI0='

cip = DES3.new(base64.standard_b64decode(CLAVE), DES3.MODE_CBC, IV=iv)
base64.b64encode(cip.encrypt('12345\x00\x00\x00'))
'25Bu+F2dMSg='
```

No soy experto en criptografia ni mucho menos, pero me resulta raro, que solo la primera llamada al método devuelve el resultado correcto, pero a partir de aquí, si los llamo sin inicializarlo, dan resultados distintos... imagino que tiene que ver con el iv. Probando, si en lugar del modo_CBC. lo invocas con MODE_ECB, los resultados ya son consistentes en la seguna y sucesivas llamadas.

Os sirve?

**Comment by bcurtu** [comment]
Los datos son diferentes porque estás usando el pedido "00012345" y yo
usaba "12345". El tema es que si el pedido no es múltiplo de 8 bytes hay
que añadirle el padding de \0 al final.

Has podido hacer una prueba así?

Gracias!

**Comment by jordic** [comment]
No he llegado a tanto... No he montado el proyecto de test aún... a ver si @alvarovelezgalvez que ya lo debe tener montado, puede probarlo :) Pero si no puede, lo puedo hacer yo mismo... pero esto ya será mañana o viernes.

**Comment by alvarovelezgalvez** [comment]
Si, hoy a última hora me pondré con esto de nuevo. Pruebo y os cuento!

2015-11-04 16:28 GMT+01:00 Jordi Collell notifications@github.com:

**Comment by alvarovelezgalvez** [comment]
Hola @jordic, ¿qué librería estás usando? ¿PyCrypto? Por la importación que haces en tu ejemplo lo parece, pero no la última versión al menos.

**Comment by jordic** [comment]
Si. Supongo q es pycrypto... Lo he importado directo del sistema. (Ubuntu15) pero cuando llegue a casa te confirmo exactamente la version

**Comment by alvarovelezgalvez** [comment]
Hola de nuevo,

Yo tanto con PyCrypto (actualizado a la 2.6, que me descarga pip) como con pyDes, obtengo los mismos valores para la clave específica por operación que los que obtiene @jordic, y me coinciden con lo que obtengo si uso el módulo php que proporciona Redsys. 

``` python
    order = '12345\x00\x00\x00'
    key = 'sq7HjrUOBfKmC576ILgskD5srU870gJ7'
    key_decoded = base64.standard_b64decode(key)

    pycrypto = DES3.new(key_decoded, DES3.MODE_CBC, IV=b'\x00\x00\x00\x00\x00\x00\x00\x00')
    pycrypto_order = pycrypto.encrypt(order)
    pycrypto_order_64 = base64.b64encode(pycrypto_order)
    print '\n\n PYCRYPTO order    --> %s' % pycrypto_order
    print '\n\n PYCRYPTO order_64 --> %s' % pycrypto_order_64

    pydes = triple_des(key_decoded, CBC, b'\x00\x00\x00\x00\x00\x00\x00\x00',  pad=b'\x00',  padmode=PAD_NORMAL)
    pydes_order  = pydes.encrypt(order)
    pydes_order_64 = base64.b64encode(pydes_order)
    print "\n\n PYDES    order    --> %s" % pydes_order
    print "\n\n PYDES    order_64 --> %s" % pydes_order_64
```

Ahora voy a ver si calculo correctamente el HMAC que me está dando error respecto a lo que calculo con el módulo PHP (que sí es correcto)

**Comment by jordic** [comment]
Perfecto, si acabo de probar y es pycrypto... no entiendo que versión tengo en la otra máquina... en la de ahora, he tenido que importar con 

```
from Crypto.Cipher import DES3
```

el reso ha funcionado igual.

**Comment by alvarovelezgalvez** [comment]
Hola, 

Ya he conseguido conectar contra el entorno de pruebas de Redsys (mediante una vista simple de Django y un template con el formulario a pelo, sin usar el módulo) y enviar un pago correctamente:

Este sería el código de la vista:

``` python
    from Crypto.Cipher import DES3
    import hashlib, json, base64, hmac

    """
        Variables inicio
    """ 
    order = '54321'
    key = 'MI_CLAVE_DE_TEST_DE_REDSYS'


    """
        Se genera una clave específica por operación. Para obtener la
        clave derivada a utilizar en una operación se debe realizar un
        cifrado 3DES entre la clave del comercio y el valor del número de
        pedido de la operación (Ds_Merchant_Order).
    """
    pycrypto = DES3.new(base64.standard_b64decode(key), DES3.MODE_CBC, IV=b'\x00\x00\x00\x00\x00\x00\x00\x00')
    pycrypto_order = pycrypto.encrypt(order.ljust(8,"\x00"))
    pycrypto_order_64 = base64.b64encode(pycrypto_order)
    print '\n\n PYCRYPTO order    --> %s' % pycrypto_order
    print '\n\n PYCRYPTO order_64 --> %s' % pycrypto_order_64


    """
        Datos iniciales. Creamos un json y los codificamos en base64 eliminando retornos de carro
    """ 
    merchant_parameters = {}
    merchant_parameters['DS_MERCHANT_AMOUNT'] = '1000'
    merchant_parameters['DS_MERCHANT_ORDER'] = order
    merchant_parameters['DS_MERCHANT_MERCHANTCODE'] = 'MI_NUMERO_DE_COMERCIO'
    merchant_parameters['DS_MERCHANT_CURRENCY'] = '978'
    merchant_parameters['DS_MERCHANT_TRANSACTIONTYPE'] = '0'
    merchant_parameters['DS_MERCHANT_TERMINAL'] = '1'
    parameters = (json.dumps(merchant_parameters)).encode()
    print '\n\n parameters --> %s' % parameters
    Ds_MerchantParameters = ''.join(unicode(base64.encodestring(parameters), 'utf-8').splitlines())
    print '\n\n Ds_MerchantParameters --> %s' % Ds_MerchantParameters


    """
        Se calcula el HMAC SHA256 del valor del parámetro
        Ds_MerchantParameters y la clave obtenida en el paso anterior.
        El resultado obtenido se codifica en BASE 64, y el resultado de la
        codificación será el valor del parámetro Ds_Signature, tal y
        como se puede observar en el ejemplo de formulario mostrado al
        inicio del apartado 3.
    """
    hmac_value = hmac.new(pycrypto_order, Ds_MerchantParameters, hashlib.sha256).digest()
    print 'hmac_value --> %s' % hmac_value
    Ds_Signature = base64.b64encode(hmac_value)
    print 'Ds_Signature --> %s' % Ds_Signature


    """
        Estos serían los tres parámetros a enviar a Redsys
    """
    context['Ds_SignatureVersion'] = 'HMAC_SHA256_V1'
    context['Ds_MerchantParameters'] = Ds_MerchantParameters
    context['Ds_Signature'] = Ds_Signature

    return render_to_response('public/test.html', context, context_instance=RequestContext(request))
```

y este el formulario (chorras):

``` html
    <form action="https://sis-t.redsys.es:25443/sis/realizarPago" method="POST" target="_blank">
        </br>Ds_SignatureVersion <input type="text" name="Ds_SignatureVersion" value="{{ Ds_SignatureVersion }}" size="50" />
        </br>Ds_Signature <input type="text" name="Ds_Signature" value="{{ Ds_Signature }}" size="150" />

        </br>Ds_MerchantParameters <input type="text" name="Ds_MerchantParameters" value="{{ Ds_MerchantParameters }}" size="50" />
        </br><input type="submit" value="Enviar" >
    </form>
```

¡Espero que os sirva!

**Comment by jordic** [comment]
Ok, pero ya que estamos, portamos el módulo, no?
@bcurtu empiezo como quieres que te ayude?

**Comment by alvarovelezgalvez** [comment]
Si si, yo puedo echar una mano tambien!

Me referia si servía para empezar!

**Comment by jordic** [comment]
A mi entender hay que portar esto, e imagino que la parte de response tambien cambia algo...
https://github.com/bcurtu/django-sermepa/blob/master/sermepa/forms.py#L31
Hay dos opciones posibles:
A. Portamos a una nueva versión del modulo, incorporando el sistema de firma nueva,
B. Creamos un setting para controlar el sistema de firma... Sabeis si el cambio de firma es para todos los bancos y cajas de redsys, o solo para algunos? Por otro lado he visto que tambien existe el módulo pyredsys.. 
No estaría de mas escribir tests para las firmas.
Como lo veis?

**Comment by alvarovelezgalvez** [comment]
Hasta donde yo se el cambio es global para todos los bancos, y ya es
accesible para todos los usuarios de redsys.

**Comment by bcurtu** [comment]
Es global para todo redsys
Alvaro, gracias, muy bien hecho.

Respecto qué hacer, bien, el cambio parece irreversible, así que lo podemos
cambiar en el core, sin gestionar versiones.

Gracias a todos por vuestra ayuda!

**Comment by alvarovelezgalvez** [comment]
Hola, he creado una rama para ir trabajando los cambios. Por ahora me he puesto con el SermepaPaymentForm:
- Ahora sólo tiene 3 campos ocultos (los que reclama RedSys) y para su inicialización, en vez del initial  que se usaba antes, ahora paso un diccionario (merchant_parameters) en el kwargs que contiene toda la información del pago a realizar.
- He integrado en el formulario los cambios que pedía RedSys --> cifrado 3DES + cálculo del HMAC

Para probar todo, he modificado la vista del paquete test y contra el entorno de test genero un botón de formulario válido para Redsys. Ahora estoy resolviendo el problema de que el DS_MERCHANT_ORDER que yo genero ha de ser menor de 8 dígitos o sino no me chuta.

P.D. Para poder currar con django 1.7 he cambiado un poco la estructura del proyecto, que me daba mucha guerra. Espero que no os cause un problema esto para probar.

**Comment by alvarovelezgalvez** [comment]
Hola de nuevo,

Parece que la generación del formulario funciona bien. Voy a ponerme ahora con la recepción de la respuesta de Redsys.

**Comment by bcurtu** [comment]
Bien hecho. cuidado con la codificación de la respuesta, viene en
base64_safe y nuestra firma es b64_strict! (Tiene que serlo)

Hay que convertir la respuesta a strict para q funcione.
Flipante

**Comment by rafapetit** [comment]
Hola. Primero que nada agradeceros vuestro trabajo.
Estoy usando sin problemas el envio del formulario.
Y he creado el mismo proceso para crear la firma de la notificacion. Extrayendo en base64 el formulario y accedo al campo Ds_Order sin problemas. 
Pero lo que es la primera palabra secreta encriptada con 3DES no me coincide. Asi que la firma final tampoco.
Se supone que cuando encriptas la clave secreta con el DS_Order deberia ser igual en los dos casos. Pregunto.

**Comment by jordic** [comment]
@rafapetit Por lo que observé, no tengo claro el porqué... aquí:

```
pycrypto = DES3.new(base64.standard_b64decode(key), DES3.MODE_CBC, IV=b'\x00\x00\x00\x00\x00\x00\x00\x00')
pycrypto_order = pycrypto.encrypt(order.ljust(8,"\x00"))
```

cada llamada a encrypt devuelve un valor distinto, pero siempre en el mismo orden... con lo que si reinicializas el objeto cada vez, debería funcionar.

Por otro lado,  si en lugar de invocarlo con el MODE_CBC, lo invocas con el MODE_ECB, los distintos resultados son iguales siempre. 

(Si hay alguien con conocimientos de cryptografia, quizá nues puede dar el razonamiento pertinente)

@alvarovelezgalvez Necesitas que te ayude en algo? Hoy le puedo dedicar algunas horas.

**Comment by alvarovelezgalvez** [comment]
Hola,

Disculpad, estoy bastante liado con otro tema y no he podido dedicarle estos días tiempo. Mañana volveré a retomarlo.

Salu2,
Álvaro

**Comment by rafapetit** [comment]
@jordic Ten encuenta que la comparativa yo la realizo primero en la creacion del formulario para enviarlo. Y despues en otro views la recepcion de la notificacion. Asi que es un objeto nuevo seguro. Ya que cada uno tiene su instancia.
Asi que sigo sin ver por donde cojerlo. Ya que por cada variacion se creara una firma diferente. Podria comprobarlas todas... ejjejej

**Comment by jordic** [comment]
@rafapetit has comprobado el comportamiento que tiene la version pho

**Comment by jordic** [comment]
s/pho/php/

**Comment by alvarovelezgalvez** [comment]
Hola, 

Creo que ya tengo todo resuelto (en mi proyecto, ahora pasaré a modificar el proyecto de django-sermepa). La única 'duda' que me ha surgido, es que en la respuesta, a la hora de comparar la firma que recibimos de RedSys y la que yo genero, tal y como decía @bcurtu respecto al strict, obtenía un error debido a los caracteres no alfanuméricos; por ejemplo:

Ds_Signature recibido   --> nD0ZrOkoUt9wRtpJ7ioy5R7vjeO-RMvXxM14Z3BpbuQ=
Ds_Signature calculado --> nD0ZrOkoUt9wRtpJ7ioy5R7vjeO+RMvXxM14Z3BpbuQ=

Lo he solucionado aplicando una expresión regular que elimina en ambas cadenas de caracteres que podían venir (/, +, - y = ) y así no tengo fallos, no sé si habría una opción mejor...

``` python
"""
    Method to check received Ds_Signature with the one we extract from Ds_MerchantParameters data.
    We remove non alphanumeric characters before doing the comparison

    @return Ds_Signature: Received signature
    @return Ds_MerchantParameters: Received parameters
    @return: True if signature is confirmed, False if not 
"""
def redsys_check_response(Ds_Signature, Ds_MerchantParameters):
    import re

    merchant_parameters = decode_parameters(Ds_MerchantParameters)
    order = merchant_parameters['Ds_Order']
    order_encrypted = encrypt_order_with_3DES(order)
    Ds_Signature_calculated = sign_hmac256(order_encrypted, Ds_MerchantParameters)

    alphanumeric_characters = re.compile('[^a-zA-Z0-9]')
    Ds_Signature_safe = re.sub(alphanumeric_characters, '', Ds_Signature)
    Ds_Signature_calculated_safe = re.sub(alphanumeric_characters, '', Ds_Signature_calculated)
    if Ds_Signature_safe  == Ds_Signature_calculated_safe:
        return True
    else:
        return False
```

**Comment by jordic** [comment]
Parece q des de apsl tb estan trabajando. @massot.

http://github.com/apsl/django-sermepa

Lo suyo sería unir fuerzas y centralizar en u solo paquete que se pueda mantener via pip.

**Comment by alvarovelezgalvez** [comment]
Hola, 

He actualizado el fork que creé el otro día (está aquí https://github.com/alvarovelezgalvez/django-sermepa ) y ya están funcionando tanto las request a Redsys como las respuestas que nos envían (así que creo que ya estaría todo...). Podéis probarlo añadiendo la secret_key nueva y el merchant_code en los settings.

Ah! También he sacado al settings el site_domain para no tener que tocar nada en la bbdd si sólo estás haciendo tests...

**Comment by rafapetit** [comment]
Gracias... Mañana lo pongo en marcha.

**Comment by bcurtu** [comment]
Gracias Álvaro.

2015-11-13 0:04 GMT+01:00 Rafa Petit notifications@github.com:

**Comment by alvarovelezgalvez** [comment]
Hola!

FYI, esta mañana he aplicado la migración a la nueva firma en mi proyecto en producción y todo está funcionando ok y sin incidencias (unas 40 compras, tanto en el terminal secure3D de Redsys como en el que no requiere doble autenticación), así que todo parece estable...

**Comment by bcurtu** [comment]
Bravo!!!

**Comment by jordic** [comment]
Bravooo!
@bcurtu mezclas con master, haces version y subes a pip? Quizá mejor si @alvarovelezgalvez te hace un pull request?

**Comment by bcurtu** [comment]
Si me hacéis un pullrequest mejor, que no tengo tiempo ni para respirar.
Gracias

2015-11-16 18:03 GMT+01:00 Jordi Collell notifications@github.com:

**Comment by alvarovelezgalvez** [comment]
Hecho!

**Comment by alvarovelezgalvez** [comment]
Genial, pues cerramos esto, ¿no?

**Comment by hellraider01** [comment]
Hola, buenas, ya se que esta cerredo este hilo. Pero con python 3.6, estoy intentando enviar la codificacion, pero no se por que me falla en la firma. Adjunto el codigo que una modificacion de lo que ya hay.

    def redsys_generate_request(self, merchant_parameters):
        Ds_MerchantParameters = self.encode_parameters(merchant_parameters)
        operation_key = self.encrypt_order_with_3DES(merchant_parameters['DS_MERCHANT_ORDER'])
        Ds_Signature = self.sign_hmac256(operation_key, Ds_MerchantParameters)
        return Ds_MerchantParameters, Ds_Signature

    def encode_parameters(self, merchant_parameters):
        parameters = (json.dumps(merchant_parameters))
        wparams = parameters.encode('utf-8')
        cdatos = base64.encodestring(wparams)
        #print(''.join(cdatos.decode('utf-8').splitlines()))
        return ''.join(cdatos.decode('utf-8').splitlines())

    def encrypt_order_with_3DES(self, Ds_Merchant_Order):
        iv = 8*b'\0'
        key = base64.b64decode(settings.SERMEPA_SECRET_KEY)
        pycrypto = DES3.new(key, DES3.MODE_CBC, IV=iv)
        padded_orded = Ds_Merchant_Order.zfill(16)
        return pycrypto.encrypt(padded_orded)

    def sign_hmac256(self, order_encrypted, Ds_MerchantParameters):
        hmac_value = hmac.new(order_encrypted, Ds_MerchantParameters.encode('utf-8'), hashlib.sha256).digest()
        b64sign = base64.b64encode(hmac_value)
        return b64sign.decode('utf-8')

alguna idea??

**Comment by jordic** [comment]
De Python 2 a 3 cambian los typos base, en py2 Los str son ASCII mientras q en py3 son Unicode. Seguramente el error viene de aquí

**Comment by alvarovelezgalvez** [comment]
Hola @hellraider01 .

Te paso las modificaciones que yo hice para hacerlo funcionar en Python3:


```
def redsys_generate_request(merchant_parameters):
    try:
        Ds_MerchantParameters = encode_parameters(merchant_parameters)
        order_encrypted = encrypt_order_with_3DES(merchant_parameters['Ds_Merchant_Order'])
        Ds_Signature = sign_hmac256(order_encrypted, Ds_MerchantParameters)
    
        return Ds_MerchantParameters, Ds_Signature
    except Exception as e:
        raise e


def redsys_check_response(Ds_Signature, Ds_MerchantParameters):
    import re

    merchant_parameters = decode_parameters(Ds_MerchantParameters)
    order = merchant_parameters['Ds_Order']
    order_encrypted = encrypt_order_with_3DES(order)
    Ds_Signature_calculated = sign_hmac256(order_encrypted, Ds_MerchantParameters)

    alphanumeric_characters = re.compile('[^a-zA-Z0-9]')
    Ds_Signature_safe = re.sub(alphanumeric_characters, '', Ds_Signature)
    Ds_Signature_calculated_safe = re.sub(alphanumeric_characters, '', Ds_Signature_calculated)
    if Ds_Signature_safe  == Ds_Signature_calculated_safe:
        return True
    else:
        logger.error('256 Signature UNmatch')
        return False


def encode_parameters(merchant_parameters):
    try:
        parameters = (json.dumps(merchant_parameters)).encode()
        return (b''.join( (base64.encodestring(parameters)).splitlines() ) ).decode('utf-8')
    except Exception as e:
        raise e


def decode_parameters(Ds_MerchantParameters):
    Ds_MerchantParameters_decoded = base64.standard_b64decode(Ds_MerchantParameters)
    return json.loads(Ds_MerchantParameters_decoded)


def encrypt_order_with_3DES(Ds_Merchant_Order):
    try:
        pycrypto = DES3.new(base64.standard_b64decode(settings.REDSYS_SECRET_KEY_256), DES3.MODE_CBC, IV='\0\0\0\0\0\0\0\0')
        order_padded = Ds_Merchant_Order.ljust(16, '\0')
        return pycrypto.encrypt(order_padded)
    except Exception as e:
        raise e


def sign_hmac256(order_encrypted, Ds_MerchantParameters):

    try:
        return (base64.b64encode( (hmac.new( order_encrypted, bytes(Ds_MerchantParameters, 'utf-8'), hashlib.sha256)).digest() ) ).decode('utf-8')
    except Exception as e:
        raise e
```

**Comment by Green-Alex** [comment]
Hola Alvaro, y todos, muchas gracias por esta explicación, la verdad es que es complicado integrar esto, en mi caso estoy con Python3 y no logro obtener la firma correctamente.

Probando el último código en Python3, en la linea 
`DES3.new(base64.standard_b64decode(settings.REDSYS_SECRET_KEY_256), DES3.MODE_CBC, IV='\0\0\0\0\0\0\0\0')`

Estoy obteniendo el error:
`Object type <class 'str'> cannot be passed to C code`
Esto entiendo que se soluciona añadiedo una b al parámetro IV para pasarlo como bytes. 

Algo parecido ocurre en la linea:
`return pycrypto.encrypt(order_padded)`
donde he también he pasado el valor de order_padded a bytes:
`return pycrypto.encrypt(bytes(order_padded, 'utf-8'))`

Con estos cambios me funciona (no me falla a mitad), pero algo me debo estar dejando porque no genera el secret correctamente ¿Hay alguna otra corrección que me este dejando?

**Comment by alvarovelezgalvez** [comment]
Hola @Green-Alex ,

El código que pegué arriba ([este](https://github.com/bcurtu/django-sermepa/issues/3#issuecomment-692593390)) es el que estoy usando en algún proyecto ahora mismo (no uso toda la librería django-sermepa ahora mismo, sólo ese código), y no tuve que pasar como bytes nada (creo recordar que alguna prueba que hice al principio lo hacía y no se me generaba bien el secret luego), tal cual está me está funcionando correctamente.

¿Cómo tienes definido el REDSYS_SECRET_KEY_256 ? ¿Tus archivos tienen encoding UTF-8? ¿Qué versión de pycrypto estás usando? Quizás va más por ahí la cosa que por cambios entre string y bytes.

**Comment by Green-Alex** [comment]
Hola @alvarovelezgalvez ,

Pues el secret es un string que cargo de un fichero de configuración como has hecho tu (tal cual nos lo indica Redsys), estoy codificando y descodificando en UTF-8 tal cual esta en tu ejemplo y uso la versión 3.9.8 de Crypto:
```
>>> import Crypto as cr
>>> print(cr.__version__)
3.9.8
```
Y estoy usando python 3.6.0. No parece haber grandes diferencias por eso me extraña que el error que obtengo al llamar al método DES3.new sin indicar que sean bytes.

Si surge alguna otra idea, cualquier ayuda es más que bienvenida, y muchas gracias!

**Comment by Green-Alex** [comment]
Hola a todos,

Solo por confirmar, finalmente el código de @alvarovelezgalvez me funcionó perfectamente, eso sí, indicando la 'b' como comentaba. 

Lo pongo a continuación por a alguien le resulta de utilidad:
```
       # Get comerce key in base64, and create the signature with 3DES encryption
        key = base64.standard_b64decode(self.config['tpv']['DS_COMERCE_KEY'])
        pycrypto = DES3.new(key, DES3.MODE_CBC, IV=b'\0\0\0\0\0\0\0\0')
        pycrypto_order = pycrypto.encrypt(order_number.ljust(16, '\0').encode('utf-8'))
        pycrypto_order_64 = base64.b64encode(pycrypto_order)

        hmac_value = hmac.new(pycrypto_order, Ds_MerchantParameters, hashlib.sha256).digest()
        Ds_Signature = base64.b64encode(hmac_value).decode('utf-8')
        Ds_Signature = Ds_Signature.replace('+', '%2B')
```
Y una cosa mas. En mi caso lo estoy montando en AWS, y corre en Lambdas. Por defecto el Python que ejecutan las lambdas de AWS no disponen de todas las librerías. En mi caso le he comentado/eliminado todas las referencias de Crypto que no uso (he dejado solo las de CBC) y además he tenido que añadir en la carpeta cypher un par de librerias de so.

Las podéis encontrar en este enlace:
https://packages.aosc.io/files/amd64/stable/pycryptodome/3.7.3-1

Muchas gracias por la ayuda!
**Alex**
